### ISSUE TITLE
How to deploy Chatgml3 with openvino to openai compatible RESTful API?

### ISSUE THREAD

**Issue by ybdesire** [OpenVINO-dev-contest/chatglm3.openvino#11]
such as `/v1/chat/completions`?

**Comment by OpenVINO-dev-contest** [comment]
We have model serving examples for LLM:

https://github.com/openvinotoolkit/model_server/tree/main/demos/python_demos/llm_text_generation

**Comment by ybdesire** [comment]
Got that. Thanks @OpenVINO-dev-contest for the help.
