### ISSUE TITLE
使用同样的方式转换glm4-9b-chat，但是报错

### ISSUE THREAD

**Issue by guardianbai86** [OpenVINO-dev-contest/chatglm3.openvino#15]
使用同样的方式转换glm4-9b-chat，但是报错，报错信息如下：
AttributeError: 'ChatGLMModel' object has no attribute 'pre_seq_len'

**Comment by OpenVINO-dev-contest** [comment]
hi, I have updated the ` requirements.txt`, please reinstall it and try again, thanks

**Comment by guardianbai86** [comment]
> hi, I have updated the ` requirements.txt`, please reinstall it and try again, thanks

您好，我更新了requirements.txt文件，然后报了这个新的错误，报错信息如下：
TypeError: compress_weights() got an unexpected keyword argument 'scale_estimation'

请问一下您的python环境是3.X?还有一个问题是，我运行代码的时候会报如下错误：
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Xaxi\\AppData\\Local\\Temp\\tmpebcy5ln5\\openvino_model.bin'
请问这是为什么呢？之前我可以转换chatglm3，但是转换成功后也会报这个信息。

**Comment by OpenVINO-dev-contest** [comment]
感觉是权限问题，你可以尝试用管理员权限运行终端

**Comment by guardianbai86** [comment]
谢谢帮助！
