### ISSUE TITLE
为什么需要重写_from_pretrained和_reshape

### ISSUE THREAD

**Issue by EveningLin** [OpenVINO-dev-contest/chatglm3.openvino#2]
刚开始接触openvino的llm应用，请问为什么需要重写_from_pretrained和_reshape

**Comment by EveningLin** [comment]
追加一个问题：在这里https://github1s.com/OpenVINO-dev-contest/ChineseLLM.openvino/blob/main/chatbot.py#L29似乎就有相关实现，两者有何区别呢

**Comment by OpenVINO-dev-contest** [comment]
Hi 这个示例的方法是封装一个继承自OVModelForCausalLM的类，这样做的好处的是可以复用Optimum-Intel和Transformers库中已经实现的pipeline，可以适配一些更复杂的场景或者配置项。

你发的第二示例里，是用numpy的方式重新构建这个pipeline，功能不会像Optimum-Intel和Transformers里的pipeline那么全，但好处是依赖没那么多，比较轻，也方便我个人梳理里面运行逻辑。
