### ISSUE TITLE
Can't download ChatGLM model files

### ISSUE THREAD

**Issue by zencorn** [OpenVINO-dev-contest/chatglm3.openvino#3]
We can't use this link download the model at all and have to download the files one by one from "Files and versions" in  https://hf-mirror.com/THUDM/chatglm3-6b/tree/main  repo.
huggingface-cli download --resume-download --local-dir-use-symlinks False THUDM/chatglm3-6b --local-dir {your_path}/chatglm3-6b

**Comment by OpenVINO-dev-contest** [comment]
Could you share your error logs ? thanks
